import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Header from "./components/Header";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Planner v2</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Header />
      <main className={styles.main}></main>
    </>
  );
};

export default Home;
