import styles from "../styles/login.module.css";
import { PrismaClient } from "@prisma/client";
import Header from "./components/Header";
import Head from "next/head";

export default function Login() {
  return (
    <Head>
      <title>Planner v2 - Login</title>
      <meta name="description" content="Generated by create-t3-app" />
    </Head>
  );
}
