import styles from "../styles/login.module.css";
import { PrismaClient } from "@prisma/client";
import Header from "./components/Header";
import Link from "next/link";
import Head from "next/head";

export default function Login() {
  return (
    <>
      <Head>
        <title>Planner v2 - Login</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Header />
      <div className={styles.main}>
        <h1 className={styles.title}>
          <Link href={"/"}>My Planner</Link>
        </h1>

        <div className={styles.formContainer}>
          <h1 className={styles.formTitle}>Login</h1>
          <form className={styles.loginForm}>
            <span className={styles.loginSpan}>
              {" "}
              Username or Email:
              <input
                type="text"
                className={styles.input}
                placeholder="Username or Email"
              />
            </span>

            <span className={styles.loginSpan}>
              Password:{" "}
              <input
                type="password"
                className={styles.input}
                placeholder="Password"
              />{" "}
            </span>
            <button className={styles.submitButton}>Log in</button>
          </form>
        </div>
      </div>
    </>
  );
}
